import { randomUUID } from "node:crypto";
import { mkdir, rm } from "node:fs/promises";
import path from "node:path";
import makeWASocket, {
  DisconnectReason,
  downloadMediaMessage,
  useMultiFileAuthState,
  type WASocket,
  type WAMessage,
} from "@whiskeysockets/baileys";
import { Boom } from "@hapi/boom";
import pino from "pino";
import { logger } from "./logger";
import {
  checkImageClaim,
  checkMediaAuthenticity,
  checkTextClaim,
  serviceProviderStatus,
  type TruthLensActivity,
} from "./truthlens-providers";

type WhatsAppState =
  | "idle"
  | "connecting"
  | "qr"
  | "connected"
  | "disconnected"
  | "error";

const authDirectory = path.resolve(
  process.cwd(),
  ".localdata/whatsapp-auth",
);
const recentActivity: TruthLensActivity[] = [];
const seenMessageIds = new Set<string>();
const metrics = {
  messagesReceived: 0,
  claimsChecked: 0,
  mediaChecked: 0,
  flaggedCount: 0,
};

let socket: WASocket | undefined;
let state: WhatsAppState = "idle";
let qrCode: string | null = null;
let phoneNumber: string | null = null;
let connectedAt: string | null = null;
let lastError: string | null = null;
let retryTimer: NodeJS.Timeout | undefined;
let manualDisconnect = false;
let connectInFlight: Promise<void> | undefined;

function pushActivity(activity: TruthLensActivity): void {
  recentActivity.unshift(activity);
  if (recentActivity.length > 30) recentActivity.length = 30;
  if (
    /likely false|ai-generated|inconclusive|mixed/i.test(activity.verdict)
  ) {
    metrics.flaggedCount += 1;
  }
  if (activity.type === "media") metrics.mediaChecked += 1;
  else metrics.claimsChecked += 1;
}

function displayName(message: WAMessage): string {
  const name = message.pushName?.trim().replace(/[\u0000-\u001f]/g, "");
  return (name || "there").slice(0, 80);
}

function extractMessage(message: WAMessage): {
  text: string;
  mediaType: "image" | "video" | null;
  mimeType: string;
  durationSeconds: number | null;
} {
  const content = message.message;
  if (!content) {
    return {
      text: "",
      mediaType: null,
      mimeType: "application/octet-stream",
      durationSeconds: null,
    };
  }
  const image = content.imageMessage;
  if (image) {
    return {
      text: image.caption ?? "",
      mediaType: "image",
      mimeType: image.mimetype ?? "image/jpeg",
      durationSeconds: null,
    };
  }
  const video = content.videoMessage;
  if (video) {
    return {
      text: video.caption ?? "",
      mediaType: "video",
      mimeType: video.mimetype ?? "video/mp4",
      durationSeconds: video.seconds ?? null,
    };
  }
  return {
    text:
      content.conversation ??
      content.extendedTextMessage?.text ??
      content.documentMessage?.caption ??
      "",
    mediaType: null,
    mimeType: "application/octet-stream",
    durationSeconds: null,
  };
}

function isGreeting(text: string): boolean {
  const normalized = text.trim().toLowerCase().replace(/[!.?,]+$/g, "");
  return /^(hi|hello|hey|heya|howdy|greetings|good\s+(morning|afternoon|evening)|what'?s?\s+up|sup|how\s+far|bawo|e\s+kaaro|e\s+kale|e\s+kaasan)(\s+there)?$/.test(
    normalized,
  );
}

function greetingReply(name: string): string {
  return [
    `Hi ${name}! 👋`,
    `I’m *TruthLens Naija*, your WhatsApp fact-checking assistant.`,
    [
      "*Here’s what I can do:*",
      "",
      "📝 Send a claim or message — I’ll check it against Google Fact Check and current web sources.",
      "",
      "🖼️ Share an image with a question — I’ll read its visible claims, then check them.",
      "",
      "🔍 Send an image or video — I’ll analyze whether it’s authentic or AI-generated.",
    ].join("\n"),
    "You’ll get a concise assessment, a confidence score, and links to sources.",
  ].join("\n\n");
}

function isAuthenticityRequest(text: string): boolean {
  return /\b(authentic|authenticity|ai[\s-]?generated|generated by ai|deepfake|genuine|real or fake|fake or real|manipulated|edited|synthetic|fabricated)\b/i.test(
    text,
  );
}

async function downloadMedia(
  message: WAMessage,
): Promise<Buffer> {
  const data = await downloadMediaMessage(message, "buffer", {});
  return Buffer.from(data);
}

async function processIncomingMessage(
  currentSocket: WASocket,
  message: WAMessage,
): Promise<void> {
  const jid = message.key.remoteJid;
  if (!jid || message.key.fromMe || jid === "status@broadcast") return;
  const id = message.key.id;
  if (id && seenMessageIds.has(id)) return;
  if (id) {
    seenMessageIds.add(id);
    if (seenMessageIds.size > 3000) {
      const first = seenMessageIds.values().next().value;
      if (first) seenMessageIds.delete(first);
    }
  }
  metrics.messagesReceived += 1;

  const senderName = displayName(message);
  const { text, mediaType, mimeType, durationSeconds } =
    extractMessage(message);

  try {
    if (!mediaType && isGreeting(text)) {
      await currentSocket.sendMessage(jid, { text: greetingReply(senderName) });
      return;
    }

    let result;
    if (
      mediaType &&
      (mediaType === "video" || isAuthenticityRequest(text))
    ) {
      if (mediaType === "video" && durationSeconds !== null && durationSeconds >= 60) {
        throw new Error(
          "Sightengine’s synchronous video check supports clips under 60 seconds. Please send a shorter clip.",
        );
      }
      const bytes = await downloadMedia(message);
      const filename =
        mediaType === "image"
          ? `whatsapp-image-${id ?? randomUUID()}.jpg`
          : `whatsapp-video-${id ?? randomUUID()}.mp4`;
      result = await checkMediaAuthenticity(
        bytes,
        mimeType,
        filename,
        mediaType,
        text,
        senderName,
      );
    } else if (mediaType === "image") {
      const bytes = await downloadMedia(message);
      result = await checkImageClaim(bytes, mimeType, text, senderName);
    } else {
      result = await checkTextClaim(text, senderName);
    }

    pushActivity(result.activity);
    await currentSocket.sendMessage(jid, { text: result.reply });
  } catch (error) {
    const messageText =
      error instanceof Error ? error.message : "The check could not be completed.";
    logger.warn(
      { mediaType, err: messageText.slice(0, 200) },
      "TruthLens message check failed",
    );
    await currentSocket.sendMessage(jid, {
      text: `*TruthLens Naija*\n\nI couldn’t complete this check: ${messageText.slice(0, 220)}\n\nNo verdict was produced. Please try again later.`,
    });
  }
}

async function startSocket(): Promise<void> {
  if (connectInFlight) return connectInFlight;
  if (state === "connected" || state === "connecting" || state === "qr") return;

  manualDisconnect = false;
  state = "connecting";
  qrCode = null;
  lastError = null;
  connectInFlight = (async () => {
    try {
      await mkdir(authDirectory, { recursive: true, mode: 0o700 });
      const { state: authState, saveCreds } =
        await useMultiFileAuthState(authDirectory);
      const currentSocket = makeWASocket({
        auth: authState,
        logger: pino({ level: "silent" }),
        printQRInTerminal: false,
        syncFullHistory: false,
        markOnlineOnConnect: false,
      });
      socket = currentSocket;
      currentSocket.ev.on("creds.update", saveCreds);
      currentSocket.ev.on("connection.update", async (update) => {
        if (update.qr) {
          qrCode = update.qr;
          state = "qr";
          lastError = null;
        }
        if (update.connection === "open") {
          state = "connected";
          qrCode = null;
          lastError = null;
          connectedAt = new Date().toISOString();
          const number = currentSocket.user?.id?.split(":")[0];
          phoneNumber = number && number.includes("@") ? number.split("@")[0] : number ?? null;
          logger.info({ phoneNumber }, "TruthLens WhatsApp connected");
        }
        if (update.connection === "close") {
          socket = undefined;
          qrCode = null;
          connectedAt = null;
          const statusCode = (update.lastDisconnect?.error as Boom | undefined)
            ?.output?.statusCode;
          const loggedOut = statusCode === DisconnectReason.loggedOut;
          const connectionError = update.lastDisconnect?.error;
          lastError =
            manualDisconnect || loggedOut
              ? null
              : connectionError
                ? String(connectionError.message ?? "Connection closed").slice(0, 200)
                : null;
          state =
            manualDisconnect || loggedOut ? "disconnected" : "error";

          if (manualDisconnect || loggedOut) {
            phoneNumber = null;
            await rm(authDirectory, { recursive: true, force: true }).catch(
              (error: unknown) =>
                logger.warn({ err: error }, "Could not clear logged-out WhatsApp session"),
            );
          } else if (!manualDisconnect) {
            if (retryTimer) clearTimeout(retryTimer);
            retryTimer = setTimeout(() => {
              void startSocket().catch((error: unknown) =>
                logger.error({ err: error }, "WhatsApp reconnection failed"),
              );
            }, 3000);
          }
          logger.warn(
            { statusCode, loggedOut, err: lastError },
            "TruthLens WhatsApp connection closed",
          );
        }
      });
      currentSocket.ev.on("messages.upsert", (event) => {
        if (event.type !== "notify") return;
        for (const incoming of event.messages) {
          void processIncomingMessage(currentSocket, incoming).catch(
            (error: unknown) =>
              logger.error({ err: error }, "WhatsApp message handler crashed"),
          );
        }
      });
    } catch (error) {
      state = "error";
      lastError =
        error instanceof Error ? error.message.slice(0, 200) : "Connection failed";
      throw error;
    } finally {
      connectInFlight = undefined;
    }
  })();
  return connectInFlight;
}

export async function resumeSavedWhatsAppSession(): Promise<void> {
  try {
    const { access } = await import("node:fs/promises");
    await access(path.join(authDirectory, "creds.json"));
  } catch {
    return;
  }
  void startSocket().catch((error: unknown) =>
    logger.error({ err: error }, "Could not resume WhatsApp session"),
  );
}

export async function connectWhatsApp(): Promise<{ message: string }> {
  await startSocket();
  return { message: "WhatsApp connection started. Scan the QR code when it appears." };
}

export async function disconnectWhatsApp(): Promise<{ message: string }> {
  manualDisconnect = true;
  if (retryTimer) {
    clearTimeout(retryTimer);
    retryTimer = undefined;
  }
  const previousSocket = socket;
  socket = undefined;
  qrCode = null;
  phoneNumber = null;
  connectedAt = null;
  lastError = null;
  state = "disconnected";
  if (previousSocket) {
    await previousSocket.logout().catch((error: unknown) => {
      logger.warn({ err: error }, "WhatsApp logout request did not complete");
      previousSocket.end(undefined);
    });
  }
  await rm(authDirectory, { recursive: true, force: true });
  return { message: "WhatsApp disconnected and its saved session was removed." };
}

export function getDashboardSnapshot() {
  return {
    whatsapp: {
      state,
      qrCode,
      phoneNumber,
      connectedAt,
      lastError,
    },
    providers: serviceProviderStatus(),
    metrics: { ...metrics },
    recentActivity: [...recentActivity],
  };
}
